In [1]:
## numpy

In [2]:
# importing library with alias
import numpy as np

In [3]:
## 1 d array
n = np.array(40)
n

array(40)

In [4]:
#.array() method is used to create an array just you have to pass in the list

# for creating single dimensional array
n1 = np.array([1 ,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

In [5]:
type(n1)

numpy.ndarray

In [6]:
# for creating multi dimensianal array you have to pass method then in it you have to pass a list and inside that you have to pass multi dimensinal array
n2 = np.array([[1,2,3,4,5]
              ,[6,7,8,9,10]])
n2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
type(n2)

numpy.ndarray

In [8]:
## 3d array
n3 = np.array([[1,2,3,4,5]
              ,[6,7,8,9,10],[10,11,12,13,14]])
n3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14]])

In [9]:
### initializing numpy with different ways 

In [10]:
#.zeros() is a method where you can initizalize arrays with zeros having just passing in the parameters in it (rows , column)

z1 = np.zeros((2 ,1))
z1

array([[0.],
       [0.]])

In [11]:
z2 = np.zeros((5 ,5))
z2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
#.full() is method where you can initialize array with same number passing in the dimnesions in () and with comma pass hte value that must be smae init

In [13]:
s1 = np.full((2 ,3 ) , 10)
s1

array([[10, 10, 10],
       [10, 10, 10]])

In [14]:
#.arange() is a method where you can pass a paticular range in intializing that array will take 3 para (Start,Stop,Step)

In [15]:
r1 = np.arange(10 , 21) # without step (it will by deafualt be 1)
r1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
r2 = np.arange(10 , 110, 10) # with step of 10
r2

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [17]:
import random

In [18]:
## now if we want to initailize array with random int numbers we have to import random and then genrate random intregers init by this
## np.random.randint() it will take 3 para (start , end , number of values)

In [19]:
r1 = np.random.randint(10,100 ,10)
r1

array([93, 24, 94, 88, 88, 47, 61, 78, 15, 34])

In [20]:
## checking shape of np array means checking there dimenisonal with the help of 
## .shape() method it is call with the list of elemwnt tore init

In [21]:
n1 = np.array([1 ,2,3,4,5])
n1.shape

(5,)

In [22]:
n2 = np.array([[1,2,3,4,5]
              ,[6,7,8,9,10]])
n2.shape

(2, 5)

In [23]:
## 1 way of checking 
## in this you are directly calling it with the alias and pass the var where arrays are stored
np.shape(n2)

(2, 5)

In [24]:
## 2 way of checking it
## directly call it with the var but you dont have to pass any thing
n2.shape

(2, 5)

In [25]:
## we can chnage the shape of that with the same method just call with var method assign it to new shape 

In [26]:
## the shape of n2 is (2,5) changing it to (5,2)
n2.shape = (5,2)

In [27]:
n2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [28]:
# a prime exmaple of changing the shape 

In [29]:
n7 = np.array([[2 , 3 , 4 ,5],[6, 7, 8, 9]])
n7

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [30]:
n7.shape

(2, 4)

In [31]:
n7.shape = (4,2)

In [32]:
n7

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
### checking dimession of array
n7.ndim

2

In [34]:
np.ndim(n7)

2

In [35]:
## we can create n dimension with the help of ndim , set its value and pass in array with a list you'll obesrve the dimension will be n 
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [36]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [37]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr3 = np.array([[9, 10], [11, 12]])

arr = np.concatenate((arr1, arr2 ,arr3), axis=1)

print(arr)

[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [40]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [51]:
## stacking is same as the concatenating
#.vstack() is method where you can vertically (column wise) stack arrays 
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
n = np.vstack((n1,n2))
print(n)
n.ndim

[[1 2 3]
 [4 5 6]]


2

In [49]:
#.hstack() is method where you can hotizontally (row wise) stack arrays 
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
n = np.hstack((n1,n2))
print(n)
n.ndim

[1 2 3 4 5 6]


1

In [50]:
#.dstack() is method where you can height (depth wise) stack arrays 
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
n = np.dstack((n1,n2))
print(n)
n.ndim

[[[1 4]
  [2 5]
  [3 6]]]


3

In [57]:
a = np.column_stack((n1,n2))
a.ndim
print(a)

[[1 4]
 [2 5]
 [3 6]]


In [58]:
### Numpy  intersection and difference method

In [60]:
## there are two methods which are to find common and unique element in 2 numy arrays
## .intersect1d() is uesd to find common value in both the numpy arrays 
## .setdiff1d() is used to find unique element in both which are not part of each other

In [63]:
n1 = np.arange(10,100,10)
n2 = np.arange(60,150,10)

In [64]:
arr1 = np.intersect1d(n1,n2)
print(arr1)

[60 70 80 90]


In [65]:
arr2 = np.setdiff1d(n1,n2)
print(arr2)

[10 20 30 40 50]


In [66]:
arr3 = np.setdiff1d(n2,n1)
print(arr3)

[100 110 120 130 140]


In [67]:
## addition of numpy arrays

In [71]:
n1 = np.arange(10,20)
n2 = np.arange(20,30)
print(n1)
print(n2)

[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]


In [73]:
## .sum([]) is used to sum up the entire 2 list of both arrays

In [70]:
Sum = np.sum([n1,n2])
print(Sum)

390


In [80]:
## if i want the sum for cloumnn we'll pass additinal parameter called axis 
## if i want to be sum along column so axis value will be zero

In [76]:
Sum_1 = np.sum([n1,n2] , axis = 0)
print(Sum_1)

[30 32 34 36 38 40 42 44 46 48]


In [78]:
## if i want to be sum along row so axis value will be one

In [79]:
Sum_2 = np.sum([n1,n2] , axis = 1)
print(Sum_2)

[145 245]


In [81]:
## scalar opreations on numpy arrays

In [87]:
n1 = np.arange(0,11,2)
print(n1)

[ 0  2  4  6  8 10]


In [88]:
## basic adiition
n1 = n1 + 1
print(n1)

[ 1  3  5  7  9 11]


In [89]:
## basic subtractrion
n1 = n1 - 1
print(n1)

[ 0  2  4  6  8 10]


In [91]:
## basic multiplication
n1 = n1 * 2
print(n1)

[ 0  4  8 12 16 20]


In [92]:
## basic division
n1 = n1 / 2
print(n1)

[ 0.  2.  4.  6.  8. 10.]


In [94]:
## for mean
m = np.mean(n1)
print(m)

5.0


In [95]:
## for standard deviation
s = np.std(n1)
print(s)

3.415650255319866


In [96]:
## for median
M = np.median(n1)
print(M)

5.0


In [97]:
## numpy matrix

In [98]:
mat = np.array([[1, 2, 3 ],[4, 5, 6],[7, 8 , 9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [102]:
# accessing rows with the help of indexing

In [99]:
mat[0]

array([1, 2, 3])

In [100]:
mat[1]

array([4, 5, 6])

In [104]:
# acessing element
mat[2][0]

7

In [111]:
## acessing column using indexing

In [107]:
mat[:,0]

array([1, 4, 7])

In [108]:
mat[:,1]

array([2, 5, 8])

In [110]:
mat[:,2]

array([3, 6, 9])

In [120]:
## .transpose() is use to take tranpose of a matirz

In [116]:
mat_T = mat.transpose() ## 1 way
mat_t = np.transpose(mat)  ## 2 way
print(mat_T)
print(mat_t)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [117]:
### numpy matrix multiplication

In [119]:
n_1 = np.array([[1 ,2 ,3 ],[4, 5, 6],[7 , 8 ,9]])
print(n_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [118]:
n_2 = np.array([[10 ,11 ,12 ],[13, 14, 15],[16 , 17 ,18]])
print(n_2)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [121]:
#.dot() is used to  multiply to matrix

In [128]:
mult1 = np.dot(n_1,n_2) # 1 way
print(mult1)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [131]:
m_t = n_1.dot(n_2)   # 2 way
print(m_t)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [129]:
mult2 = np.dot(n_2,n_1) # 1 way
print(mult2)

[[138 171 204]
 [174 216 258]
 [210 261 312]]


In [130]:
m_tt = n_2.dot(n_1)   # 2 way
print(m_tt)

[[138 171 204]
 [174 216 258]
 [210 261 312]]


In [138]:
### numpy save and load
##  .save() is used to save the file it takes two parameter 1 name of file and 2 what to save
##  .load() is used to load that file u haave to use .npy extension with it 

In [134]:
num_1 = np.arange(10,100,20)
print(num_1)

[10 30 50 70 90]


In [136]:
np.save("Array 1",num_1)

In [137]:
np.load("Array 1.npy")

array([10, 30, 50, 70, 90])